### ISSUE TITLE
Async HTTP example points to wrong domain!

### ISSUE THREAD

**Issue by TommyCocchi** [calamity-inc/Stand-Example-Scripts#1]
extreme issue:

https://github.com/calamity-inc/Stand-Example-Scripts/blob/main/Async%20HTTP.pluto

points to stand.gg

😸

**Comment by Sainan** [comment]
Good point. Reminds me I should probably also add an example of doing HTTP using the new Pluto library.

**Comment by TommyCocchi** [comment]
New pluto library?
